// snn.c — 2-layer spiking MLP, integer only (no FPU on PicoRV32).
//
// Mirrors the snnTorch model in code/snn_keyword/train_keyword_snn.py
// (Leaky neurons, threshold 1.0, reset by subtraction with snnTorch's
// one-step reset delay). The weights come from weights.h, generated by
// code/snn_keyword/export_weights.py, which also holds a bit-exact Python
// copy of this function — change both together.
//
// Fixed point: Q(SNN_Q) for weights, biases and membranes; inputs are
// uint8 in Q(SNN_X_SHIFT).

#include "snn.h"
#include "weights.h"

#define ONE (1 << SNN_Q)

// one LIF step: leak, integrate, subtract threshold if it spiked last step
static inline int32_t lif_step(int32_t mem, int32_t cur, int32_t beta)
{
    int32_t reset = mem > ONE ? ONE : 0;
    return (int32_t)(((int64_t)beta * mem) >> SNN_Q) + cur - reset;
}

void snn_run(const uint8_t *x, uint32_t *counts)
{
    int32_t cur1[SNN_N_HID], mem1[SNN_N_HID], mem2[SNN_N_OUT];

    // Rate encoding feeds the same input every step, so the layer-1 input
    // current is constant: compute it once (this is ~all of the MACs).
    for (int j = 0; j < SNN_N_HID; j++) {
        int32_t acc = 0;
        for (int i = 0; i < SNN_N_IN; i++)
            acc += snn_w1[j][i] * (int32_t)x[i];
        cur1[j] = (acc >> SNN_X_SHIFT) + snn_b1[j];
        mem1[j] = 0;
    }
    for (int k = 0; k < SNN_N_OUT; k++) {
        mem2[k] = 0;
        counts[k] = 0;
    }

    for (int t = 0; t < SNN_T; t++) {
        int32_t cur2[SNN_N_OUT];
        for (int k = 0; k < SNN_N_OUT; k++)
            cur2[k] = snn_b2[k];

        // hidden layer; spikes are binary, so layer 2 is just adds
        for (int j = 0; j < SNN_N_HID; j++) {
            mem1[j] = lif_step(mem1[j], cur1[j], SNN_BETA1);
            if (mem1[j] > ONE)
                for (int k = 0; k < SNN_N_OUT; k++)
                    cur2[k] += snn_w2[k][j];
        }

        for (int k = 0; k < SNN_N_OUT; k++) {
            mem2[k] = lif_step(mem2[k], cur2[k], SNN_BETA2);
            if (mem2[k] > ONE)
                counts[k]++;
        }
    }
}
