// test_snn.c — HOST-side check that snn.c matches the Python integer model.
// Not part of the firmware. Build + run on the PC, e.g.:
//   cc -O2 -I. test_snn.c snn.c -o test_snn && ./test_snn
// test_vectors.h is generated by code/snn_keyword/export_weights.py.

#include <stdio.h>

#include "snn.h"
#include "weights.h"
#include "test_vectors.h"

int main(void)
{
    int bad = 0;
    for (int v = 0; v < N_VEC; v++) {
        uint32_t c[SNN_N_OUT];
        snn_run(vec_x[v], c);
        int ok = c[0] == vec_counts[v][0] && c[1] == vec_counts[v][1];
        printf("vec %d: C (%u, %u)  python (%u, %u)  %s\n", v, c[0], c[1],
               vec_counts[v][0], vec_counts[v][1], ok ? "ok" : "MISMATCH");
        bad += !ok;
    }
    printf(bad ? "FAIL\n" : "PASS\n");
    return bad != 0;
}
