#!/usr/bin/env python3
"""export_weights.py — trained SNN -> integer weights for the RISC-V firmware.

Reads runs/keyword_snn.pt, quantizes it to fixed point and writes
../pynqz2_riscv_flow/firmware/weights.h. It then runs a bit-exact Python
model of the firmware's integer forward pass (firmware/snn.c) on the test
set, so you can see what quantization costs before touching the board.

Fixed-point scheme (must match firmware/snn.c):
  * input  x in [0,1]  ->  uint8  xq = min(255, round(x * 256))
  * weights, biases, membrane, threshold in Q12 (1.0 == 4096)
  * layer 1 current  = (W1q . xq) >> 8  +  b1q     (constant over time:
                       rate encoding repeats the same input every step)
  * LIF step         = (beta_q * mem) >> 12  +  cur  -  (mem_prev > 1.0 ? 1.0 : 0)
  * spike            = mem > 1.0

Run:  python export_weights.py   (after train_keyword_snn.py)
"""

import os

import numpy as np
import torch

from train_keyword_snn import (DATA_DIR, KEYWORD, N_TIMESTEPS, OUT_DIR,
                               SpikeMLP, evaluate, fmt, rate_encode)

Q = 12
ONE = 1 << Q
X_SHIFT = 8                      # xq is x in Q8
FW_DIR = os.path.join("..", "pynqz2_riscv_flow", "firmware")


def quantize(net):
    sd = net.state_dict()

    def q(t, dtype, lim):
        a = np.round(t.detach().numpy().astype(np.float64) * ONE).astype(np.int64)
        assert np.abs(a).max() < lim, "weight out of range for its C type"
        return a.astype(dtype)

    return {
        "w1": q(sd["fc1.weight"], np.int16, 1 << 15),
        "b1": q(sd["fc1.bias"], np.int32, 1 << 31),
        "w2": q(sd["fc2.weight"], np.int16, 1 << 15),
        "b2": q(sd["fc2.bias"], np.int32, 1 << 31),
        "beta1": int(round(float(net.lif1.beta) * ONE)),
        "beta2": int(round(float(net.lif2.beta) * ONE)),
    }


def quantize_input(x):
    """float features in [0,1] -> uint8, exactly what the board receives."""
    return np.minimum(255, np.round(np.asarray(x) * 256)).astype(np.uint8)


def int_forward(p, xq):
    """Bit-exact model of firmware/snn.c. xq: [B, N_IN] uint8 -> counts [B, 2]."""
    xq = xq.astype(np.int64)
    cur1 = ((xq @ p["w1"].T.astype(np.int64)) >> X_SHIFT) + p["b1"]
    mem1 = np.zeros_like(cur1)
    mem2 = np.zeros((xq.shape[0], p["w2"].shape[0]), dtype=np.int64)
    counts = np.zeros_like(mem2)
    for _ in range(N_TIMESTEPS):
        mem1 = ((p["beta1"] * mem1) >> Q) + cur1 - np.where(mem1 > ONE, ONE, 0)
        spk1 = (mem1 > ONE).astype(np.int64)
        cur2 = spk1 @ p["w2"].T.astype(np.int64) + p["b2"]
        mem2 = ((p["beta2"] * mem2) >> Q) + cur2 - np.where(mem2 > ONE, ONE, 0)
        counts += mem2 > ONE
    return counts


def c_array(name, ctype, a):
    rows = a.reshape(a.shape[0], -1) if a.ndim > 1 else a.reshape(1, -1)
    dims = "".join(f"[{d}]" for d in a.shape)
    body = ",\n".join("    " + ("{" if a.ndim > 1 else "") +
                      ", ".join(str(int(v)) for v in r) +
                      ("}" if a.ndim > 1 else "") for r in rows)
    return f"static const {ctype} {name}{dims} = {{\n{body}\n}};\n"


def write_header(p, path):
    n_hid, n_in = p["w1"].shape
    with open(path, "w") as f:
        f.write(f"""// weights.h — GENERATED by code/snn_keyword/export_weights.py. Do not edit.
// Keyword "{KEYWORD}" SNN, fixed point Q{Q} (1.0 == {ONE}).

#ifndef WEIGHTS_H
#define WEIGHTS_H

#include <stdint.h>

#define SNN_N_IN    {n_in}
#define SNN_N_HID   {n_hid}
#define SNN_N_OUT   {p["w2"].shape[0]}
#define SNN_T       {N_TIMESTEPS}
#define SNN_Q       {Q}
#define SNN_X_SHIFT {X_SHIFT}
#define SNN_BETA1   {p["beta1"]}
#define SNN_BETA2   {p["beta2"]}

""")
        f.write(c_array("snn_w1", "int16_t", p["w1"]) + "\n")
        f.write(c_array("snn_b1", "int32_t", p["b1"]) + "\n")
        f.write(c_array("snn_w2", "int16_t", p["w2"]) + "\n")
        f.write(c_array("snn_b2", "int32_t", p["b2"]) + "\n")
        f.write("#endif // WEIGHTS_H\n")


def main():
    net = SpikeMLP()
    net.load_state_dict(torch.load(os.path.join(OUT_DIR, "keyword_snn.pt")))
    p = quantize(net)

    path = os.path.join(FW_DIR, "weights.h")
    write_header(p, path)
    print(f"wrote {path}")

    # float model vs integer firmware model on the test split
    x, y = torch.load(os.path.join(DATA_DIR, f"{KEYWORD}_test_features.pt"))
    loader = torch.utils.data.DataLoader(
        torch.utils.data.TensorDataset(x, y), batch_size=256)
    print(f"float   test: {fmt(evaluate(net, loader))}")

    counts = int_forward(p, quantize_input(x.reshape(x.shape[0], -1)))
    pred = torch.from_numpy((counts[:, 1] > counts[:, 0]).astype(np.int64))
    tp = int(((pred == 1) & (y == 1)).sum()); fn = int(((pred == 0) & (y == 1)).sum())
    fp = int(((pred == 1) & (y == 0)).sum()); tn = int(((pred == 0) & (y == 0)).sum())
    print(f"integer test: " + fmt({"acc": (tp + tn) / len(y),
                                   "recall": tp / max(1, tp + fn),
                                   "false_alarm": fp / max(1, fp + tn)}))

    # a few test vectors for the host-side C check (firmware/test_snn.c)
    xq = quantize_input(x[:8].reshape(8, -1))
    with open(os.path.join(FW_DIR, "test_vectors.h"), "w") as f:
        f.write("// test_vectors.h — GENERATED by export_weights.py (host test only)\n")
        f.write("#include <stdint.h>\n#define N_VEC 8\n")
        f.write(c_array("vec_x", "uint8_t", xq))
        f.write(c_array("vec_counts", "uint32_t", int_forward(p, xq)))


if __name__ == "__main__":
    main()
