// spike_top.v — top level of the minimal RISC-V / SNN bring-up design.
//
// Instantiates the PS block design (Zynq PS7 + AXI interconnect + protocol
// converter, generated by vivado/build.tcl as ps_bd) and two independent
// RISC-V subsystems (no shared memory; see rtl/ps_if.v for the address map).
// The only board I/O is the 10-bit LED bank: core 0's firmware drives it, and
// the PS can read either core's LED value back through that core's syscon.
//
// Power-on reset: por_cnt is released 16 clocks after configuration, so both
// CPUs stay in reset until the PS loads firmware and clears their CTRL bit0.

module spike_top (
    inout wire [14:0] DDR_addr,
    inout wire [2:0] DDR_ba,
    inout wire DDR_cas_n, DDR_ck_n, DDR_ck_p, DDR_cke, DDR_cs_n,
    inout wire [3:0] DDR_dm,
    inout wire [31:0] DDR_dq,
    inout wire [3:0] DDR_dqs_n, DDR_dqs_p,
    inout wire DDR_odt, DDR_ras_n, DDR_reset_n, DDR_we_n,
    inout wire FIXED_IO_ddr_vrn, FIXED_IO_ddr_vrp,
    inout wire [53:0] FIXED_IO_mio,
    inout wire FIXED_IO_ps_clk, FIXED_IO_ps_porb, FIXED_IO_ps_srstb,
    output wire [9:0] led          // PYNQ-Z2 board LEDs (see ps_if LED register)
);

    // ------------------------------------------------------------------
    // Clock + power-on reset
    // ------------------------------------------------------------------
    wire fclk;

    reg [4:0] por_cnt = 5'd0;
    always @(posedge fclk)
        if (!por_cnt[4])
            por_cnt <= por_cnt + 1'b1;
    wire aresetn = por_cnt[4];

    // ------------------------------------------------------------------
    // Block design: PS7 M_AXI_GP0 -> interconnect -> protocol converter
    // -> external AXI4-Lite master port M00_AXI
    // ------------------------------------------------------------------
    wire [31:0] m00_awaddr;
    wire        m00_awvalid, m00_awready;
    wire [31:0] m00_wdata;
    wire [3:0]  m00_wstrb;
    wire        m00_wvalid, m00_wready;
    wire [1:0]  m00_bresp;
    wire        m00_bvalid, m00_bready;
    wire [31:0] m00_araddr;
    wire        m00_arvalid, m00_arready;
    wire [31:0] m00_rdata;
    wire [1:0]  m00_rresp;
    wire        m00_rvalid, m00_rready;

    ps_bd_wrapper u_bd (
        .DDR_addr(DDR_addr), .DDR_ba(DDR_ba), .DDR_cas_n(DDR_cas_n),
        .DDR_ck_n(DDR_ck_n), .DDR_ck_p(DDR_ck_p), .DDR_cke(DDR_cke),
        .DDR_cs_n(DDR_cs_n), .DDR_dm(DDR_dm), .DDR_dq(DDR_dq),
        .DDR_dqs_n(DDR_dqs_n), .DDR_dqs_p(DDR_dqs_p), .DDR_odt(DDR_odt),
        .DDR_ras_n(DDR_ras_n), .DDR_reset_n(DDR_reset_n), .DDR_we_n(DDR_we_n),
        .FIXED_IO_ddr_vrn(FIXED_IO_ddr_vrn), .FIXED_IO_ddr_vrp(FIXED_IO_ddr_vrp),
        .FIXED_IO_mio(FIXED_IO_mio), .FIXED_IO_ps_clk(FIXED_IO_ps_clk),
        .FIXED_IO_ps_porb(FIXED_IO_ps_porb), .FIXED_IO_ps_srstb(FIXED_IO_ps_srstb),
        .FCLK_CLK0        (fclk),
        .aresetn          (aresetn),
        .M00_AXI_awaddr   (m00_awaddr),
        .M00_AXI_awprot   (),
        .M00_AXI_awvalid  (m00_awvalid),
        .M00_AXI_awready  (m00_awready),
        .M00_AXI_wdata    (m00_wdata),
        .M00_AXI_wstrb    (m00_wstrb),
        .M00_AXI_wvalid   (m00_wvalid),
        .M00_AXI_wready   (m00_wready),
        .M00_AXI_bresp    (m00_bresp),
        .M00_AXI_bvalid   (m00_bvalid),
        .M00_AXI_bready   (m00_bready),
        .M00_AXI_araddr   (m00_araddr),
        .M00_AXI_arprot   (),
        .M00_AXI_arvalid  (m00_arvalid),
        .M00_AXI_arready  (m00_arready),
        .M00_AXI_rdata    (m00_rdata),
        .M00_AXI_rresp    (m00_rresp),
        .M00_AXI_rvalid   (m00_rvalid),
        .M00_AXI_rready   (m00_rready)
    );

    // ------------------------------------------------------------------
    // PS interface (AXI-Lite slave + one syscon per core)
    // ------------------------------------------------------------------
    localparam integer NUM_CORES = 2;

    wire [NUM_CORES-1:0]    core_rst;        // 1 = CPU held in reset
    wire [NUM_CORES-1:0]    bram_we;
    wire [16*NUM_CORES-1:0] bram_addr;
    wire [32*NUM_CORES-1:0] bram_wdata;
    wire [4*NUM_CORES-1:0]  bram_be;
    wire [32*NUM_CORES-1:0] bram_rdata;
    wire [32*NUM_CORES-1:0] scratch;
    wire [32*NUM_CORES-1:0] timer_lo;
    wire [NUM_CORES-1:0]    core_running, core_trap;
    wire [10*NUM_CORES-1:0] led_o;

    ps_if #(
        .CLK_HZ    (32'd100_000_000),
        .NUM_CORES (NUM_CORES)
    ) u_ps_if (
        .aclk            (fclk),
        .aresetn         (aresetn),
        .s_axil_awaddr   (m00_awaddr),
        .s_axil_awvalid  (m00_awvalid),
        .s_axil_awready  (m00_awready),
        .s_axil_wdata    (m00_wdata),
        .s_axil_wstrb    (m00_wstrb),
        .s_axil_wvalid   (m00_wvalid),
        .s_axil_wready   (m00_wready),
        .s_axil_bresp    (m00_bresp),
        .s_axil_bvalid   (m00_bvalid),
        .s_axil_bready   (m00_bready),
        .s_axil_araddr   (m00_araddr),
        .s_axil_arvalid  (m00_arvalid),
        .s_axil_arready  (m00_arready),
        .s_axil_rdata    (m00_rdata),
        .s_axil_rresp    (m00_rresp),
        .s_axil_rvalid   (m00_rvalid),
        .s_axil_rready   (m00_rready),
        .bram_we         (bram_we),
        .bram_addr       (bram_addr),
        .bram_wdata      (bram_wdata),
        .bram_be         (bram_be),
        .bram_rdata      (bram_rdata),
        .core_rst        (core_rst),
        .core_running    (core_running),
        .core_trap       (core_trap),
        .timer_now       (timer_lo),
        .scratch         (scratch),
        .led             (led_o)
    );

    // ------------------------------------------------------------------
    // RISC-V subsystems: two independent copies, each with its own BRAM,
    // reset (its own syscon CTRL bit) and free-running timer.
    // ------------------------------------------------------------------
    spike_soc #(
        .MEM_WORDS (65536)     // 256 KB
    ) u_soc0 (
        .clk         (fclk),
        .core_rst_n  (~core_rst[0]),
        .pa_we       (bram_we[0]),
        .pa_addr     (bram_addr[15:0]),
        .pa_wdata    (bram_wdata[31:0]),
        .pa_be       (bram_be[3:0]),
        .pa_rdata    (bram_rdata[31:0]),
        .core_running(core_running[0]),
        .core_trap   (core_trap[0]),
        .timer_lo    (timer_lo[31:0]),
        .led_o       (led_o[9:0])
    );

    spike_soc #(
        .MEM_WORDS (65536)     // 256 KB
    ) u_soc1 (
        .clk         (fclk),
        .core_rst_n  (~core_rst[1]),
        .pa_we       (bram_we[1]),
        .pa_addr     (bram_addr[31:16]),
        .pa_wdata    (bram_wdata[63:32]),
        .pa_be       (bram_be[7:4]),
        .pa_rdata    (bram_rdata[63:32]),
        .core_running(core_running[1]),
        .core_trap   (core_trap[1]),
        .timer_lo    (timer_lo[63:32]),
        .led_o       (led_o[19:10])
    );

    // ------------------------------------------------------------------
    // Board LEDs (driven by core 0's LED register)
    // ------------------------------------------------------------------
    assign led = led_o[9:0];
    // led_o[19:10] (core 1) is intentionally not on a pin: the board has only
    // one LED bank. The PS still reads it through core 1's syscon LED register.

endmodule
