#!/usr/bin/env python3
"""Export one extended-encoding checkpoint for PicoRV32 verification."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import torch

import extended_encoding_sweep as sweep
import frontend_sweep as base


WEIGHT_SCALE = 64
BETA_Q8 = round(0.9 * 256)


def quantize_weights(state: dict[str, torch.Tensor]) -> dict[str, np.ndarray]:
    w1 = np.rint(state["fc1.weight"].numpy() * WEIGHT_SCALE)
    w2 = np.rint(state["fc2.weight"].numpy() * WEIGHT_SCALE)
    if max(np.abs(w1).max(), np.abs(w2).max()) > 127:
        raise ValueError("weight exceeds int8 range")
    return {
        "w1": w1.astype(np.int8),
        "b1": np.rint(state["fc1.bias"].numpy() * WEIGHT_SCALE * 255).astype(np.int32),
        "w2": w2.astype(np.int8),
        "b2": np.rint(state["fc2.bias"].numpy() * WEIGHT_SCALE).astype(np.int32),
    }


def integer_counts(params: dict[str, np.ndarray], features: np.ndarray) -> np.ndarray:
    qx = np.rint(np.clip(features, 0.0, 1.0) * 255).astype(np.int32)
    current1 = qx @ params["w1"].astype(np.int32).T + params["b1"]
    mem1 = np.zeros_like(current1)
    mem2 = np.zeros((len(features), 2), dtype=np.int32)
    counts = np.zeros_like(mem2)
    for _ in range(sweep.TIMESTEPS):
        mem1 = ((mem1 * BETA_Q8) >> 8) + current1
        spike1 = mem1 >= WEIGHT_SCALE * 255
        mem1 -= spike1.astype(np.int32) * WEIGHT_SCALE * 255
        current2 = spike1.astype(np.int32) @ params["w2"].astype(np.int32).T
        current2 += params["b2"]
        mem2 = ((mem2 * BETA_Q8) >> 8) + current2
        spike2 = mem2 >= WEIGHT_SCALE
        mem2 -= spike2.astype(np.int32) * WEIGHT_SCALE
        counts += spike2.astype(np.int32)
    return counts


def c_values(values: np.ndarray, per_line: int = 16) -> str:
    flat = [str(int(value)) for value in values.reshape(-1)]
    return "\n".join(
        "    " + ", ".join(flat[start : start + per_line]) + ","
        for start in range(0, len(flat), per_line)
    )


def write_header(
    path: Path,
    params: dict[str, np.ndarray],
    cfg: sweep.EncodingConfig,
    decision_threshold: int,
    keyword: str,
) -> None:
    text = f"""// Generated by research/export_extended_candidate.py.
#ifndef KEYWORD_MODEL_H
#define KEYWORD_MODEL_H

#define KW_KEYWORD \"{keyword}\"
#define KW_INPUTS {cfg.inputs}
#define KW_HIDDEN {sweep.HIDDEN}
#define KW_OUTPUTS 2
#define KW_TIMESTEPS {sweep.TIMESTEPS}
#define KW_BETA_Q8 {BETA_Q8}
#define KW_WEIGHT_SCALE {WEIGHT_SCALE}
#define KW_THRESHOLD1 {WEIGHT_SCALE * 255}
#define KW_THRESHOLD2 {WEIGHT_SCALE}
#define KW_DECISION_MARGIN {decision_threshold}
#define KW_MIN_KEYWORD_SPIKES 0
#define KW_FEATURE_BITS {cfg.bits}
#define KW_FEATURE_BANDS {cfg.bands}
#define KW_FEATURE_CHANNELS {cfg.channels}
#define KW_FEATURE_TIME_BINS {cfg.time_bins}
#define KW_FEATURE_LOW_HZ {cfg.low_hz}
#define KW_FEATURE_HIGH_HZ {cfg.high_hz}
#define KW_FEATURE_DURATION_MS {cfg.duration_ms}

static const int8_t kw_w1[KW_HIDDEN * KW_INPUTS] = {{
{c_values(params['w1'])}
}};

static const int32_t kw_b1[KW_HIDDEN] = {{
{c_values(params['b1'], 8)}
}};

static const int8_t kw_w2[KW_OUTPUTS * KW_HIDDEN] = {{
{c_values(params['w2'])}
}};

static const int32_t kw_b2[KW_OUTPUTS] = {{
{c_values(params['b2'], 8)}
}};

#endif
"""
    path.write_text(text, encoding="ascii", newline="\n")


def write_board_audio_features(path: Path, cfg: sweep.EncodingConfig) -> None:
    text = f'''"""Generated packet validator for an encoding-sweep candidate."""
import struct
import numpy as np

N_MELS = {cfg.board_rows}
N_TIME = {cfg.time_bins}
N_INPUTS = N_MELS * N_TIME
PACKET_MAGIC = b"KWS1"
PACKET_HEADER = struct.Struct("<4sIHH")

def unpack_frame(packet):
    if len(packet) < PACKET_HEADER.size:
        raise ValueError("packet is shorter than the keyword header")
    magic, sequence, rows, cols = PACKET_HEADER.unpack_from(packet)
    if magic != PACKET_MAGIC:
        raise ValueError("bad packet magic")
    if (rows, cols) != (N_MELS, N_TIME):
        raise ValueError(f"unsupported feature shape {{(rows, cols)}}")
    payload = packet[PACKET_HEADER.size:]
    if len(payload) != N_INPUTS:
        raise ValueError(f"expected {{N_INPUTS}} payload bytes, got {{len(payload)}}")
    return sequence, np.frombuffer(payload, dtype=np.uint8).reshape(rows, cols)
'''
    path.write_text(text, encoding="ascii", newline="\n")


def export_candidate(
    checkpoint_path: Path,
    dataset: Path,
    keyword: str,
    feature_cache: Path,
    output: Path,
) -> dict:
    checkpoint = torch.load(checkpoint_path, map_location="cpu", weights_only=True)
    run = checkpoint["run"]
    cfg = sweep.EncodingConfig(**run["config"])
    params = quantize_weights(checkpoint["state_dict"])
    features = np.load(feature_cache, mmap_mode="r")
    paths, labels, speakers = base.discover_dataset(dataset, keyword)
    split = base.dataset_split(dataset, paths, speakers)
    validation = np.flatnonzero(split == "val")

    validation_counts = integer_counts(params, np.asarray(features[validation]))
    validation_margin = validation_counts[:, 1] - validation_counts[:, 0]
    threshold = base.choose_threshold(labels[validation], validation_margin)

    positive = validation[labels[validation] == 1][:20]
    negative = validation[labels[validation] == 0][:20]
    vector_index = np.r_[positive, negative]
    vector_counts = integer_counts(params, np.asarray(features[vector_index]))

    output.mkdir(parents=True, exist_ok=True)
    write_header(output / "keyword_model.h", params, cfg, threshold, keyword)
    write_board_audio_features(output / "audio_features.py", cfg)
    np.savez_compressed(
        output / "board_vectors.npz",
        x=np.rint(np.asarray(features[vector_index]) * 255).astype(np.uint8),
        y=labels[vector_index],
        counts=vector_counts,
        paths=np.array([str(paths[index]) for index in vector_index]),
    )
    report = {
        "checkpoint": str(checkpoint_path.resolve()),
        "keyword": keyword,
        "config": run["config"],
        "integer_validation": base.metrics(
            labels[validation], validation_margin >= threshold
        ),
        "decision_threshold": threshold,
        "vectors": len(vector_index),
        "parameter_bytes": int(sum(value.nbytes for value in params.values())),
    }
    (output / "export.json").write_text(
        json.dumps(report, indent=2), encoding="utf-8"
    )
    return report


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("checkpoint", type=Path)
    parser.add_argument("--dataset", type=Path, required=True)
    parser.add_argument("--keyword", default="sheila")
    parser.add_argument("--feature-cache", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    report = export_candidate(
        args.checkpoint,
        args.dataset,
        args.keyword,
        args.feature_cache,
        args.output,
    )
    print(json.dumps(report, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
