#!/usr/bin/env python3
"""Quantize a frontend-sweep checkpoint and export board verification data."""

from __future__ import annotations

import argparse
import json
from dataclasses import asdict
from pathlib import Path

import numpy as np
import torch

import frontend_sweep as sweep


WEIGHT_SCALE = 64
BETA_Q8 = round(0.9 * 256)


def quantize(state: dict[str, torch.Tensor]) -> dict[str, np.ndarray]:
    w1 = np.rint(state["fc1.weight"].numpy() * WEIGHT_SCALE)
    w2 = np.rint(state["fc2.weight"].numpy() * WEIGHT_SCALE)
    if max(np.abs(w1).max(), np.abs(w2).max()) > 127:
        raise ValueError("weight exceeds int8 range")
    return {
        "w1": w1.astype(np.int8),
        "b1": np.rint(
            state["fc1.bias"].numpy() * WEIGHT_SCALE * 255
        ).astype(np.int32),
        "w2": w2.astype(np.int8),
        "b2": np.rint(state["fc2.bias"].numpy() * WEIGHT_SCALE).astype(np.int32),
    }


def integer_counts(params: dict[str, np.ndarray], x: np.ndarray) -> np.ndarray:
    qx = np.rint(np.clip(x, 0.0, 1.0) * 255).astype(np.int32)
    current1 = qx @ params["w1"].astype(np.int32).T + params["b1"]
    mem1 = np.zeros_like(current1)
    mem2 = np.zeros((len(x), 2), dtype=np.int32)
    counts = np.zeros_like(mem2)
    threshold1 = WEIGHT_SCALE * 255
    threshold2 = WEIGHT_SCALE
    for _ in range(sweep.TIMESTEPS):
        mem1 = ((mem1 * BETA_Q8) >> 8) + current1
        spike1 = mem1 >= threshold1
        mem1 -= spike1.astype(np.int32) * threshold1
        current2 = spike1.astype(np.int32) @ params["w2"].astype(np.int32).T
        current2 += params["b2"]
        mem2 = ((mem2 * BETA_Q8) >> 8) + current2
        spike2 = mem2 >= threshold2
        mem2 -= spike2.astype(np.int32) * threshold2
        counts += spike2.astype(np.int32)
    return counts


def c_values(values: np.ndarray, per_line: int = 16) -> str:
    flat = [str(int(value)) for value in values.reshape(-1)]
    return "\n".join(
        "    " + ", ".join(flat[start:start + per_line]) + ","
        for start in range(0, len(flat), per_line)
    )


def write_header(
    path: Path,
    params: dict[str, np.ndarray],
    config: sweep.FeatureConfig,
    decision_threshold: int,
    keyword: str,
) -> None:
    text = f"""// Generated by research/export_frontend_candidate.py.
#ifndef KEYWORD_MODEL_H
#define KEYWORD_MODEL_H

#define KW_KEYWORD \"{keyword}\"
#define KW_INPUTS {config.inputs}
#define KW_HIDDEN {sweep.HIDDEN}
#define KW_OUTPUTS 2
#define KW_TIMESTEPS {sweep.TIMESTEPS}
#define KW_BETA_Q8 {BETA_Q8}
#define KW_WEIGHT_SCALE {WEIGHT_SCALE}
#define KW_THRESHOLD1 {WEIGHT_SCALE * 255}
#define KW_THRESHOLD2 {WEIGHT_SCALE}
#define KW_DECISION_MARGIN {decision_threshold}
#define KW_MIN_KEYWORD_SPIKES 0
#define KW_FEATURE_BITS {config.bits}
#define KW_FEATURE_BANDS {config.bands}
#define KW_FEATURE_TIME_BINS {sweep.TIME_BINS}
#define KW_FEATURE_LOW_HZ {config.low_hz}
#define KW_FEATURE_HIGH_HZ {config.high_hz}
#define KW_FEATURE_DURATION_MS {config.duration_ms}

static const int8_t kw_w1[KW_HIDDEN * KW_INPUTS] = {{
{c_values(params['w1'])}
}};

static const int32_t kw_b1[KW_HIDDEN] = {{
{c_values(params['b1'], 8)}
}};

static const int8_t kw_w2[KW_OUTPUTS * KW_HIDDEN] = {{
{c_values(params['w2'])}
}};

static const int32_t kw_b2[KW_OUTPUTS] = {{
{c_values(params['b2'], 8)}
}};

#endif
"""
    path.write_text(text, encoding="ascii", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("checkpoint", type=Path)
    parser.add_argument("--dataset", type=Path, required=True)
    parser.add_argument("--keyword", required=True)
    parser.add_argument("--feature-cache", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    checkpoint = torch.load(args.checkpoint, map_location="cpu", weights_only=True)
    run = checkpoint["run"]
    config = sweep.FeatureConfig(**run["config"])
    params = quantize(checkpoint["state_dict"])
    x = np.load(args.feature_cache, mmap_mode="r")
    paths, labels, speakers = sweep.discover_dataset(args.dataset, args.keyword)
    split = sweep.dataset_split(args.dataset, paths, speakers)
    val_index = np.flatnonzero(split == "val")
    test_index = np.flatnonzero(split == "test")

    val_counts = integer_counts(params, np.asarray(x[val_index]))
    val_margin = val_counts[:, 1] - val_counts[:, 0]
    threshold = sweep.choose_threshold(labels[val_index], val_margin)
    test_counts = integer_counts(params, np.asarray(x[test_index]))
    test_margin = test_counts[:, 1] - test_counts[:, 0]

    positive = test_index[labels[test_index] == 1][:20]
    negative = test_index[labels[test_index] == 0][:20]
    vector_index = np.r_[positive, negative]
    vector_counts = integer_counts(params, np.asarray(x[vector_index]))

    args.output.mkdir(parents=True, exist_ok=True)
    write_header(
        args.output / "keyword_model.h", params, config, threshold, args.keyword
    )
    np.savez_compressed(
        args.output / "board_vectors.npz",
        x=np.rint(np.asarray(x[vector_index]) * 255).astype(np.uint8),
        y=labels[vector_index],
        counts=vector_counts,
        paths=np.array([str(paths[index]) for index in vector_index]),
    )
    report = {
        "checkpoint": str(args.checkpoint.resolve()),
        "keyword": args.keyword,
        "config": asdict(config),
        "integer_validation": sweep.metrics(labels[val_index], val_margin >= threshold),
        "integer_test": sweep.metrics(labels[test_index], test_margin >= threshold),
        "decision_threshold": threshold,
        "vectors": len(vector_index),
        "parameter_bytes": int(
            sum(value.nbytes for value in params.values())
        ),
    }
    (args.output / "export.json").write_text(
        json.dumps(report, indent=2), encoding="utf-8"
    )
    print(json.dumps(report, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
